apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-todo
  template:
    metadata:
      labels:
        app: go-todo
    spec:
      containers:
        - name: go-todo
          image: awabahmed/todo:v3
          ports:
            - containerPort: 4040
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS
          readinessProbe:
            httpGet:
              path: /
              port: 4040
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 4040
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-todo-service
spec:
  selector:
    app: go-todo
  ports:
    - port: 4040
      targetPort: 4040
  type: ClusterIP
