name: Docker CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/muhammad-awab/go-todo

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ env.SHORT_SHA }} .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ env.SHORT_SHA }}

      - name: Update docker-compose.yml with new tag
        run: |
          sed -i "s|image: ghcr.io/muhammad-awab/go-todo:.*|image: ghcr.io/muhammad-awab/go-todo:${{ env.SHORT_SHA }}|" docker-compose.yml

      - name: Commit updated docker-compose.yml
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "chore: update docker image tag to ${{ env.SHORT_SHA }}"
          git push
